// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClm1Sz8mojGXRjia5WzBY0fmcsmgFooJ0',
    appId: '1:963251815440:web:e1b3314f500adf1b68f695',
    messagingSenderId: '963251815440',
    projectId: 'myfirstflutterproject-74fc7',
    authDomain: 'myfirstflutterproject-74fc7.firebaseapp.com',
    storageBucket: 'myfirstflutterproject-74fc7.appspot.com',
    measurementId: 'G-8FHJWYMV7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfT6PwYJKVAG29ktctD4gmT2A1moSYnSE',
    appId: '1:963251815440:android:37a9ebaf2d5f581468f695',
    messagingSenderId: '963251815440',
    projectId: 'myfirstflutterproject-74fc7',
    storageBucket: 'myfirstflutterproject-74fc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJDq0LkMxptJrPGqKNCuwqMjxRMT0oz5o',
    appId: '1:963251815440:ios:04d1cd342521838668f695',
    messagingSenderId: '963251815440',
    projectId: 'myfirstflutterproject-74fc7',
    storageBucket: 'myfirstflutterproject-74fc7.appspot.com',
    iosClientId: '963251815440-ckpv3b9prdod92n43snd69boid9av1pn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJDq0LkMxptJrPGqKNCuwqMjxRMT0oz5o',
    appId: '1:963251815440:ios:04d1cd342521838668f695',
    messagingSenderId: '963251815440',
    projectId: 'myfirstflutterproject-74fc7',
    storageBucket: 'myfirstflutterproject-74fc7.appspot.com',
    iosClientId: '963251815440-ckpv3b9prdod92n43snd69boid9av1pn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
